version: "3"
services:
  db:
    image: "postgres:10.5"
    restart: "unless-stopped"
    ports:
      - "5432:5432"
    volumes:
      # Postgres volumes don't map well from Windows partitions - ownership problem.
      # Either use named volumes or local storage only.
      #- ./db/data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "project"
